config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }


  #admin側


  #user側
  root to:'user/homes#top'
  resources :customers, only: [:new, :create, :index, :show, :destroy, :edit , :update], to: 'user/customers#'
  resources :histories, only: [:new, :create, :edit, :update, :destroy], to: 'user/histories#'

  resources :users, only: [:edit, :update], to: 'user/users#'
  get '/users/my_page', to:'user/users#show'


  #検索
  get 'search' => 'user/customers#search'





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord

  belongs_to :user
  has_many :histories, dependent: :destroy

#検索
  def self.search(keyword)
  where(["customer_name like? OR address like?", "%#{keyword}%", "%#{keyword}%"])
  end
  
  validates :customer_name, presence: true
  validates :address, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #アソシエーション
  has_many :customers, dependent: :destroy
  has_many :histories, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/user/customers_controller.rb
class User::CustomersController < ApplicationController

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    @customer.user_id = current_user.id
    if @customer.save
      flash[:notice]="You have creatad customer successfully."
      redirect_to customers_path(@customer)
    else
      @user = current_user
      @customers = Customer.all
      render :new
    end
  end

  def index
    @user = current_user
    @customers = Customer.all.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer =Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    if customer.update(customer_params)
      redirect_to customer_path(customer.id)
    else
      @customer = Customer.find(params[:id])
      render :edit
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_path
  end

  def search
    @customers = Customer.search(params[:keyword])
    @keyword = params[:keyword]
    render "index"
  end

  private

  def customer_params
    params.require(:customer).permit(:customer_name, :memo, :telephone_number, :address, :manager)
  end

end

app/controllers/user/histories_controller.rb
class User::HistoriesController < ApplicationController

  def new
    @history =History.new
    @customer = params[:customer_id]
  end

  def edit
    @history =History.find(params[:id])
  end

  def update
    history = History.find(params[:id])
    if history.update(history_params)
      redirect_to customer_path(history.customer_id)
    else
      @history = History.find(params[:id])
      render :edit
    end
  end

  def create
    #customer = Customer.find(params[:customer_id])
    history = current_user.histories.new(history_params)
    #history.customer_id = customer.id
    history.save
    redirect_to customer_path(history.customer_id)
  end

  def destroy
    @history = History.find(params[:id])
    @history.destroy
    redirect_to customer_path
  end

  def history_params
    params.require(:history).permit(:id, :user_id, :customer_id, :action, :result, :caption)
  end

end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    user = current_user
    if user.update(user_params)
      redirect_to users_my_page_path
    else
      @user=current_user
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:id,:name, :email)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user/customers_helper.rb
module User::CustomersHelper
end

app/helpers/user/histories_helper.rb
module User::HistoriesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/customers/edit.html.erb
<div class="containar">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">

<h2 class="text-dark bg-light p-4 mb-0">新規企業登録</h2>
      <div class="form-body p-4">
        <%= form_with model: @customer, local:true do |f| %>

        <h4>企業名</h4>
        <%= f.text_field :customer_name ,class:"form-control" %>
        <h4>住所</h4>
        <%= f.text_field :address ,class:"form-control"%>
        <h4>連絡先</h4>
        <%= f.text_field :telephone_number ,class:"form-control" %>
        <h4>担当者</h4>
        <%= f.text_field :manager ,class:"form-control"%>

        <h4>メモ</h4>
        <%= f.text_area :memo ,class:"form-control"  %>
        <%= f.submit '変更を登録' , class:"btn btn-lg btn-block btn-info mt-4" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user/customers/index.html.erb
<main>
  <div class="container">

    <div class="search-form">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword, value: @keyword %>
    <%= f.submit "検索" ,class:"btn-success"%>
  <% end %>
    </div>


    <h3 style="margin-top:20px;">顧客一覧</h3>
    <div class="text-right index-new" style ="margin-bottom:20;">
    <%= link_to new_customer_path do %>
      <button type="button" class="btn btn-circle btn-lg">＋</button>
    <% end %>
  </div>
    <table class="table">
      <tr>
        <td>
          顧客名
        </td>
        <td>
          住所
        </td>
        <td>
          ステータス
        </td>
        <td>

        </td>
        <td>

        </td>
      </tr>
      <%@customers.each do |customer|%>
      <tr>
        <td>
          <%= customer.customer_name %>
        </td>
        <td>
          <%= customer.address %>
        </td>
        <td>
          ー
        </td>
        <td>
          <%= link_to '顧客詳細',customer_path(customer.id), class:"btn btn-success" %>
        </td>
        <td>

        </td>
      </tr>
      <%end%>
    </table>
    <%= paginate @customers %>
  </div>
</main>

app/views/user/customers/new.html.erb
<div class="containar">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">

<h2 class="text-dark bg-light p-4 mb-0">新規企業登録</h2>
      <div class="form-body p-4">
        <%= form_with model: @customer, local:true do |f| %>

        <h4>企業名</h4>
        <%= f.text_field :customer_name ,class:"form-control" %>
        <h4>住所</h4>
        <%= f.text_field :address ,class:"form-control"%>
        <h4>連絡先</h4>
        <%= f.text_field :telephone_number ,class:"form-control" %>
        <h4>担当者</h4>
        <%= f.text_field :manager ,class:"form-control"%>

        <h4>メモ</h4>
        <%= f.text_area :memo ,class:"form-control"  %>
        <%= f.submit '登録' , class:"btn btn-lg btn-block btn-info mt-4" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user/customers/show.html.erb
<main>
  <div class="container">
    <h3 style="margin-top:20px;">顧客詳細</h3>
    <table class="table table-borderless">
      <tr>
        <th>
          顧客名
        </th>
        <td>
          <%= @customer.customer_name %>
        </td>
      </tr>
      <tr>
        <th>
          住所
        </th>
        <td>
          <%= @customer.address %>
        </td>
      </tr>
      <tr>
        <th>
          電話番号
        </th>
        <td>
          <%= @customer.telephone_number %>
        </td>
      </tr>
      <tr>
        <th>
          担当者
        </th>
        <td>
          <%= @customer.manager %>
        </td>
      </tr>
      <tr>
        <th>
          メモ
        </th>
        <td>
          <%= @customer.memo%>
        </td>
      </tr>
    </table>
    <%= link_to '編集する',edit_customer_path, class:"btn btn-success" %>
    <%= link_to "顧客情報を削除する", customer_path(@customer.id), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %>
    <%= link_to '顧客履歴の追加',new_history_path(customer_id: @customer.id), class:"btn btn-primary" %>

    <%#= paginate @customers %>



<h3 style="margin-top:20px;">履歴一覧</h3>

    <table class="table">
      <tr>
        <td>
          投稿日
        </td>
        <td>
          アクション
        </td>
        <td>
          結果
        </td>
        <td>
          次回行動・メモ
        </td>
      </tr>
      <%@customer.histories.each do |history|%>
      <tr>
        <td>
          <%= history.created_at.strftime('%Y/%m/%d') %>
        </td>
        <td>
          <%= history.action %>
        </td>
        <td>
          <%= history.result %>
        </td>
        <td>
          <%= history.caption %>
        </td>
        <td>
              <%= link_to "顧客情報を削除する", history_path(history.id), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %>
        </td>
      </tr>
      <%end%>
    </table>
    <%#= paginate @historys %>
  </div>
</main>