config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }


  #admin側


  #user側
  root to:'user/homes#top'
  resources :customers, only: [:new, :create, :index, :show, :destroy, :edit , :update], to: 'user/customers#'
  resources :histories, only: [:new, :create, :edit, :update, :destroy], to: 'user/histories#'

  resources :users, only: [:edit, :update], to: 'user/users#'
  get '/users/my_page', to:'user/users#show'


  #検索
  get 'search' => 'user/customers#search'





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>CustomerRecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header class="border-bottom">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href='/'>
          <span>stareco</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <div class="container">
              <div class="row">
                <%if user_signed_in?%>
                　<div class="col">
                    <li>
                      ようこそ、<%= current_user.name%>さん！
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to 'マイページ', users_my_page_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to '顧客一覧', customers_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>


                <%else%>
                  <div class="col my-2">
                    <li>
                      <%#= link_to 'About', about_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to '新規登録', new_user_registration_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                  <div class="col my-2">
                    <li>
                      <%= link_to 'ログイン', new_user_session_path, class: "btn btn-outline-secondary" %>
                    </li>
                  </div>
                <%end%>
              </div>
            </div>
          </ul>
        </div>
      </nav>
    </header>
    <%= yield %>

<footer>
    <div class=" text-white pt-3 pb-4">
        <div class="row no-gutters col-md-10 offset-md-2">
          <div class="col-md-4">
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3"><a href="/">お問い合わせ</a></h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">会社概要</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
              </li>
            </ul>
          </div>
        </div>

    </div>
  </footer>
  </body>
</html>